# Generated by Django 4.1.7 on 2023-03-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('color', models.CharField(max_length=255, null=True, verbose_name='Цвет')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('availability', models.BooleanField(verbose_name='Наличие')),
            ],
            options={
                'verbose_name': 'Полотна',
                'verbose_name_plural': 'Полотна',
            },
        ),
    ]
