# Generated by Django 4.1.7 on 2023-03-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
