# Generated by Django 4.1.7 on 2023-03-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0002_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
