# Generated by Django 4.1.7 on 2023-03-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='celings',
            name='price_installation',
            field=models.IntegerField(default=0, verbose_name='Цена с установкой'),
        ),
    ]
