# Generated by Django 4.1.7 on 2023-03-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0003_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='color',
            field=models.CharField(default='', max_length=255, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='corners',
            field=models.IntegerField(default=0, verbose_name='Углы'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='invoice',
            field=models.CharField(default='', max_length=255, verbose_name='Фактура'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='light',
            field=models.IntegerField(default=0, verbose_name='Точек света'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='material',
            field=models.CharField(default='', max_length=255, verbose_name='Материял'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pipe',
            field=models.IntegerField(default=0, verbose_name='Обходов труб'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='room',
            field=models.CharField(default='', max_length=255, verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='section',
            field=models.CharField(default='', max_length=255, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='square',
            field=models.FloatField(default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Загаловок'),
        ),
    ]
