# Generated by Django 4.1.7 on 2023-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0004_portfolio_description_alter_portfolio_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
