# Generated by Django 4.1.7 on 2023-03-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0004_celings_price_installation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celings',
            name='price_installation',
        ),
    ]
