# Generated by Django 4.1.7 on 2023-03-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0005_remove_celings_price_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('material', models.CharField(max_length=255, verbose_name='Материял')),
                ('invoice', models.CharField(max_length=255, verbose_name='Фактура')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('corners', models.IntegerField(verbose_name='Углы')),
                ('section', models.CharField(max_length=255, verbose_name='Профиль')),
                ('light', models.IntegerField(verbose_name='Точек света')),
                ('pipe', models.IntegerField(verbose_name='Обходов труб')),
            ],
            options={
                'verbose_name': 'Карточка портфолио',
                'verbose_name_plural': 'Карточки портфолио',
            },
        ),
    ]
