# Generated by Django 4.1.7 on 2023-03-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0006_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='room',
            field=models.CharField(default=0, max_length=255, verbose_name='Помещение'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.ImageField(upload_to='', verbose_name='Фото')),
                ('portfolioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceiling.portfolio')),
            ],
            options={
                'verbose_name': 'Фотография к портфолио',
                'verbose_name_plural': 'Фотографии к портфолио',
            },
        ),
    ]
