# Generated by Django 4.1.7 on 2023-03-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0007_portfolio_room_portfoliophoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliophoto',
            old_name='square',
            new_name='img',
        ),
    ]
