# Generated by Django 4.1.7 on 2023-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0008_rename_square_portfoliophoto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliophoto',
            name='img',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
    ]
