# Generated by Django 4.1.7 on 2023-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceiling', '0010_portfoliophoto_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
